# Generated by Django 4.2.13 on 2024-11-06 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='position',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='emergency_phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Company Employee ID', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_programming_languages',
            field=models.TextField(blank=True, help_text='Preferred programming languages (comma-separated)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_work_hours',
            field=models.CharField(blank=True, help_text="e.g., '9 AM - 5 PM EST'", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_skills',
            field=models.TextField(blank=True, help_text='Main technical skills (comma-separated)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_skills',
            field=models.TextField(blank=True, help_text='Secondary technical skills (comma-separated)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stackoverflow_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('JUNIOR', 'Junior Developer'), ('MID', 'Mid-Level Developer'), ('SENIOR', 'Senior Developer'), ('LEAD', 'Team Lead'), ('MANAGER', 'Project Manager'), ('ARCHITECT', 'Software Architect'), ('DEVOPS', 'DevOps Engineer'), ('QA', 'QA Engineer')], default='JUNIOR', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
