# Generated by Django 4.2.13 on 2024-11-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_position_userprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='github_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='github_organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='github_project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='is_github_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNING', max_length=20),
        ),
    ]
